Update speedtest/Dockerfile & Remove helper script as it's no longer needed
.cirrus.yml
speedtest/Dockerfile
speedtest/helper.sh

diff --git a/speedtest/Dockerfile b/speedtest/Dockerfile
--- a/speedtest/Dockerfile
+++ b/speedtest/Dockerfile
@@ -11,20 +11,22 @@ RUN apk --no-cache add wget bash
 
 # Build time Environment Variable
 ARG VERSION="1.0.0"
-ARG SHELL=/bin/bash
-
-# Copy helper script
-COPY speedtest/helper.sh /tmp/helper.sh
+ARG TARGETPLATFORM
+ARG BUILDPLATFORM
+ARG SHELL=/usr/bin/bash
 
 # Install Speedtest CLI
+RUN wget --quiet --output-document /tmp/speedtest.tar.tgz https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-"${TARGETPLATFORM}"-linux.tgz || \
+    echo "Getting Speedtest Failed!" && \
+    exit 1
+
 RUN cd /tmp && \
-    bash helper.sh && \
     tar xf /tmp/speedtest.tar.tgz && \
     mv ./speedtest /usr/bin && \
-    rm speedtest* helper.sh
+    rm speedtest*
 
 # Cleaning up
-RUN apk --no-cache del wget bash
+RUN apk --no-cache del wget
 
 # Accept license & run it
 RUN speedtest --accept-license || \
