Update speedtest/Dockerfile
Attemp to fix Multi Arch Docker Image(s)

diff --git a/speedtest/Dockerfile b/speedtest/Dockerfile
--- a/speedtest/Dockerfile
+++ b/speedtest/Dockerfile
@@ -15,7 +15,11 @@ ARG VERSION="1.0.0"
 # Install Speedtest CLI
 RUN set -ex && \
     ARCH=$(arch) && \
-    wget --quiet --output-document /tmp/speedtest.tar.tgz https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-"${ARCH}"-linux.tgz
+    if ! wget --quiet --output-document /tmp/speedtest.tar.tgz https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-"${ARCH}"-linux.tgz; \
+    then \
+        echo "Getting Speedtest Failed"; \
+        exit 1; \
+    fi
 
 RUN cd /tmp && \
     tar xf /tmp/speedtest.tar.tgz && \
